
services:
  ###> doctrine/doctrine-bundle ###
  db_maquette:
    image: mariadb:latest
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3320:3306"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3320
      MYSQL_ROOT_PASSWORD: appui*23
      MYSQL_DATABASE: maquette
      MYSQL_USER: maquette
      MYSQL_PASSWORD: maquette

  maquette:
    build: .
    restart: always
    volumes:
      - .:/var/www/
    ports:
      - "9965:80"
    depends_on:
      - db_maquette
      # this command is used to execute installations that must be performed on live server
    #command: >
      #bash -c "php bin/console doctrine:schema:update --force  && apache2-foreground"
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

