version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      # You should definitely change the password in production
        MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        MYSQL_USER: ${MYSQL_USER:-app}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
    ports:
      - "3306:3306"
